-- PostgreSQL schema for FYP Submission Management System
-- Sensitive columns store encrypted data (AES-256-GCM)

CREATE TABLE IF NOT EXISTS users (
  user_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name_encrypted TEXT NOT NULL,
  email_hash TEXT NOT NULL UNIQUE,
  email_encrypted TEXT NOT NULL,
  password_hash TEXT NOT NULL,
  role VARCHAR(50) CHECK (role IN ('admin', 'lecturer', 'student')),
  created_by INTEGER REFERENCES users(user_id) ON DELETE SET NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS password_reset_tokens (
  token_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
  token_hash TEXT NOT NULL UNIQUE,
  expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
  used_at TIMESTAMP WITH TIME ZONE,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS students (
  student_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL UNIQUE REFERENCES users(user_id) ON DELETE CASCADE,
  matric_no VARCHAR(50) NOT NULL UNIQUE,
  course VARCHAR(150) NOT NULL,
  intake VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS lecturers (
  lecturer_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL UNIQUE REFERENCES users(user_id) ON DELETE CASCADE,
  staff_id VARCHAR(50) NOT NULL UNIQUE,
  department VARCHAR(150) NOT NULL
);

CREATE TABLE IF NOT EXISTS projects (
  project_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title_encrypted TEXT NOT NULL,
  description_encrypted TEXT,
  category_encrypted TEXT,
  lecturer_id INTEGER REFERENCES users(user_id) ON DELETE SET NULL,
  study_year INTEGER CHECK (study_year BETWEEN 1 AND 5),
  progress_percentage INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS project_members (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id INTEGER NOT NULL REFERENCES projects(project_id) ON DELETE CASCADE,
  user_id INTEGER NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
  role VARCHAR(50) NOT NULL,
  UNIQUE (project_id, user_id)
);

CREATE TABLE IF NOT EXISTS files (
  file_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id INTEGER NOT NULL REFERENCES projects(project_id) ON DELETE CASCADE,
  file_name_encrypted TEXT NOT NULL,
  file_path_encrypted TEXT NOT NULL,
  uploaded_by INTEGER REFERENCES users(user_id) ON DELETE SET NULL,
  uploaded_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  UNIQUE (project_id, file_name_encrypted)
);

CREATE TABLE IF NOT EXISTS file_versions (
  version_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  file_id INTEGER NOT NULL REFERENCES files(file_id) ON DELETE CASCADE,
  version_number INTEGER NOT NULL,
  file_path_encrypted TEXT NOT NULL,
  uploaded_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  UNIQUE (file_id, version_number)
);

CREATE TABLE IF NOT EXISTS comments (
  comment_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id INTEGER NOT NULL REFERENCES projects(project_id) ON DELETE CASCADE,
  user_id INTEGER REFERENCES users(user_id) ON DELETE SET NULL,
  content_encrypted TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS comment_visibility (
  comment_id INTEGER NOT NULL REFERENCES comments(comment_id) ON DELETE CASCADE,
  user_id INTEGER NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
  hidden_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  PRIMARY KEY (comment_id, user_id)
);

CREATE TABLE IF NOT EXISTS submissions (
  submission_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id INTEGER NOT NULL REFERENCES projects(project_id) ON DELETE CASCADE,
  submitted_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  status VARCHAR(50) CHECK (status IN ('pending','approved','rejected'))
);

CREATE TABLE IF NOT EXISTS notifications (
  notification_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  recipient_user_id INTEGER NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
  sender_user_id INTEGER REFERENCES users(user_id) ON DELETE SET NULL,
  project_id INTEGER REFERENCES projects(project_id) ON DELETE SET NULL,
  notification_type VARCHAR(50) NOT NULL,
  message TEXT NOT NULL,
  is_read BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

-- Optional indexes
CREATE INDEX IF NOT EXISTS idx_projects_lecturer ON projects (lecturer_id);
CREATE INDEX IF NOT EXISTS idx_password_reset_tokens_user ON password_reset_tokens (user_id);
CREATE INDEX IF NOT EXISTS idx_password_reset_tokens_hash ON password_reset_tokens (token_hash);
CREATE INDEX IF NOT EXISTS idx_students_user ON students (user_id);
CREATE INDEX IF NOT EXISTS idx_lecturers_user ON lecturers (user_id);
CREATE INDEX IF NOT EXISTS idx_files_project ON files (project_id);
CREATE INDEX IF NOT EXISTS idx_file_versions_file ON file_versions (file_id);
CREATE INDEX IF NOT EXISTS idx_comments_project ON comments (project_id);
CREATE INDEX IF NOT EXISTS idx_submissions_project ON submissions (project_id);
